server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

pullData: ${TRAM_PULLDATA:- false}
filterData: ${TRAM_FILTER:- true}
rebuildGraph: ${TRAM_GRAPH:- true}
graphName: buses.db
closedStations:
  - St Peters Square
agencies:
  - "*"
instanceDataUrl: http://169.254.169.254
awsRegionName: eu-west-1
tramDataUrl: ${TRAM_DATAURL:- http://odata.tfgm.com/opendata/downloads/TfGMgtfs.zip}
dataPath: data/bus
timeWindow: 60
showMyLocation: true
nearestStopRangeKM: 2
numOfNearestStops: 6
walkingMPH: 3
redirectHTTP: ${REDIRECTHTTP:- false}

genericMapper: true
createLocality: true

logging:
  level: DEBUG
  loggers:
    root: INFO
    com.tramchester: DEBUG
    org.eclipse.jetty.servlet: INFO
    io.dropwizard.jersey.jackson: INFO

  appenders:
    - type: console
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: log/tramchester.log
      threshold: INFO
      archive: true
      archivedLogFilenamePattern: log/tramchester-%d.log
      archivedFileCount: 5
      timeZone: UTC
