server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  connector:
    type: http
    port: 8090

rebuildGraph: false

logging:
  level: INFO
  loggers:
    root: INFO
    com.rubix: DEBUG
    com.yammer.dropwizard: INFO
    com.yammer.dropwizard.jersey: DEBUG
    org.eclipse.jetty.servlet": DEBUG
    io.dropwizard.jersey.jackson: DEBUG

  appenders:
    - type: console
