server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

rebuildGraph: true

logging:
  level: INFO
  loggers:
    root: INFO
    com.tramchester: DEBUG
    org.eclipse.jetty.servlet": DEBUG
    io.dropwizard.jersey.jackson: DEBUG

  appenders:
    - type: console
