server:
  type: simple
  applicationContextPath: /
  rootPath: /api/*
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

rebuildGraph: true
pullData: false
graphName: tramchester.db
closedStations:
  - St Peters Square

logging:
  level: INFO
  loggers:
    root: INFO
    com.tramchester: DEBUG
    org.eclipse.jetty.servlet: DEBUG
    io.dropwizard.jersey.jackson: DEBUG

  appenders:
    - type: console
    - type: syslog
      host: localhost
      port: 514
    - type: file
      currentLogFilename: log/tramchester.log
      threshold: ALL
      archive: true
      archivedLogFilenamePattern: log/tramchester-%d.log
      archivedFileCount: 5
      timeZone: UTC
